version: '3.8'

services:
  web:
    build: .
    ports:
      - "8001:8000"
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: default_user
      POSTGRES_PASSWORD: default_password
      POSTGRES_DB: default_db
    ports:
      - "5434:5432"
